test: simplify test workflow

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -11,9 +11,13 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
+env:
+  PY_COLORS: "1"
+  IMAGE_NAME: conda-forge-tick
+
 jobs:
   check:
-    name: Check if we can skip the merge queue
+    name: check if we can skip the merge queue
     outputs:
       skip-check: ${{ steps.merge-queue-ci-skipper.outputs.skip-check }}
     runs-on: ubuntu-slim
@@ -25,12 +29,398 @@ jobs:
             secret: ${{ secrets.AUTOTICK_BOT_TOKEN }}
 
   tests:
+    name: tests
+    runs-on: "ubuntu-latest"
     needs: check
-    uses: ./.github/workflows/tests-reusable.yml
-    with:
-      skip: ${{ needs.check.outputs.skip-check }}
-    secrets:
-      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
-      BOT_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
-      BOT_APP_ID: ${{ secrets.CF_BOT_DATA_MANAGER_APP_ID }}
-      BOT_PRIVATE_KEY: ${{ secrets.CF_BOT_DATA_MANAGER_PRIVATE_KEY }}
+    permissions:
+      actions: write  # for deleting cache entries
+      contents: read
+    env:
+      NUM_SPLITS: 8
+    strategy:
+      # continue running the tests even if one of the groups fails
+      fail-fast: false
+      matrix:
+        # if change the number of groups here, also change number of splits env var
+        group: [1, 2, 3, 4, 5, 6, 7, 8]
+    defaults:
+      run:
+        shell: bash -leo pipefail {0}
+
+    steps:
+      - name: free disk space
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        uses: endersonmenezes/free-disk-space@2a22f8c59cae9cddae7194b33e6b92d023b2b4b8 # v4.0.0
+        with:
+          remove_android: true
+          remove_dotnet: true
+          remove_haskell: true
+          rm_cmd: "rmz"
+
+      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          repository: "conda-forge/conda-forge-bot"
+
+      - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          environment-file: conda-lock.yml
+          environment-name: conda-forge-bot
+          condarc-file: autotick-bot/condarc
+
+      - name: configure conda and install code
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          pip install --no-deps --no-build-isolation -e .
+
+      - name: Set up git
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          git config --global user.name regro-cf-autotick-bot
+          git config --global user.email 36490558+regro-cf-autotick-bot@users.noreply.github.com
+          git config --global pull.rebase false
+
+      - name: test versions
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          cd ..
+          python -c "import conda_forge_tick; assert conda_forge_tick.__version__ != '0.0.0'"
+          cd -
+
+          pip uninstall conda-forge-tick --yes
+          rm -rf dist/*
+          python -m build --sdist . --outdir dist
+          pip install --no-deps --no-build-isolation dist/*.tar.gz
+          cd ..
+          python -c "import conda_forge_tick; assert conda_forge_tick.__version__ != '0.0.0'"
+          cd -
+          pip uninstall conda-forge-tick --yes
+
+          python -m pip install -v --no-deps --no-build-isolation -e .
+
+      - name: get version
+        id: version
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          ver=$(python -c "import conda_forge_tick; print(conda_forge_tick.__version__)")
+          echo "version=${ver}" >> "$GITHUB_OUTPUT"
+
+      - name: build docker image
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
+        with:
+          image: ${{ env.IMAGE_NAME }}
+          tags: test
+          containerfiles: |
+            ./Dockerfile
+          extra-args: |
+            --no-cache
+            --squash
+          build-args: |
+            SETUPTOOLS_SCM_PRETEND_VERSION=${{ steps.version.outputs.version }}
+
+      - name: push image to docker
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
+        with:
+          image: conda-forge-tick
+          tags: test
+          registry: "docker-daemon:docker.io/library"
+
+      - name: checkout docker image sizes
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          docker images
+
+      - name: restore test durations
+        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          path: .test_durations
+          key: test-durations-${{ github.ref }}-${{ github.sha }}
+          restore-keys: |
+            test-durations-${{ github.ref }}-
+            test-durations-
+
+      - name: post-process test durations
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          if [[ -f .test_durations ]]; then
+            cp .test_durations .test_durations.${{ matrix.group }}
+          fi
+
+      - name: run pytest
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          export TEST_BOT_TOKEN_VAL=unpassword
+          pytest \
+            -v \
+            -n 3 \
+            --splits ${NUM_SPLITS} --group ${{ matrix.group }} \
+            --store-durations \
+            --durations-path=.test_durations.${{ matrix.group }} \
+            --splitting-algorithm least_duration \
+            --clean-durations \
+            --cov=conda_forge_tick \
+            --cov=tests \
+            --cov-config=.coveragerc \
+            --cov-report=term-missing \
+            --cov-report=xml \
+            --durations=10 \
+            --retries=5 \
+            --retry-delay=10 \
+            -m "not mongodb" \
+            tests
+        env:
+          RUN_URL: ""
+          BOT_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
+          BOT_APP_ID: ${{ secrets.CF_BOT_DATA_MANAGER_APP_ID }}
+          BOT_PRIVATE_KEY: ${{ secrets.CF_BOT_DATA_MANAGER_PRIVATE_KEY }}
+
+      - name: upload test durations
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          name: test-durations-${{ matrix.group }}
+          path: .test_durations.${{ matrix.group }}
+          include-hidden-files: true
+
+      - name: upload coverage
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          name: coverage-${{ matrix.group }}
+          path: .coverage
+          include-hidden-files: true
+
+  tests-mongodb:
+    name: tests-mongodb
+    runs-on: "ubuntu-latest"
+    needs: check
+    permissions:
+      actions: write  # for deleting cache entries
+      contents: read
+    strategy:
+      # continue running the tests even if one of the groups fails
+      fail-fast: false
+      matrix:
+        # if change the number of groups here, also change it next to --splits below
+        group: [1]
+    defaults:
+      run:
+        shell: bash -leo pipefail {0}
+
+    steps:
+      - name: free disk space
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        uses: endersonmenezes/free-disk-space@2a22f8c59cae9cddae7194b33e6b92d023b2b4b8 # v4.0.0
+        with:
+          remove_android: true
+          remove_dotnet: true
+          remove_haskell: true
+          rm_cmd: "rmz"
+
+      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          repository: "conda-forge/conda-forge-bot"
+
+      - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          environment-file: conda-lock.yml
+          environment-name: conda-forge-bot
+          condarc-file: autotick-bot/condarc
+
+      - name: configure conda and install code
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          pip install --no-deps --no-build-isolation -e .
+
+      - name: Set up git
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          git config --global user.name regro-cf-autotick-bot
+          git config --global user.email 36490558+regro-cf-autotick-bot@users.noreply.github.com
+          git config --global pull.rebase false
+
+      - name: test versions
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          cd ..
+          python -c "import conda_forge_tick; assert conda_forge_tick.__version__ != '0.0.0'"
+          cd -
+
+          pip uninstall conda-forge-tick --yes
+          rm -rf dist/*
+          python -m build --sdist . --outdir dist
+          pip install --no-deps --no-build-isolation dist/*.tar.gz
+          cd ..
+          python -c "import conda_forge_tick; assert conda_forge_tick.__version__ != '0.0.0'"
+          cd -
+          pip uninstall conda-forge-tick --yes
+
+          python -m pip install -v --no-deps --no-build-isolation -e .
+
+      - name: start MongoDB
+        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # v1.12.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          mongodb-version: "latest"
+
+      - name: test mongodb is OK
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          python -c "from pymongo import MongoClient; import os; print(MongoClient(os.environ['MONGODB_CONNECTION_STRING']))"
+        env:
+          MONGODB_CONNECTION_STRING: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000"
+
+      - name: restore test durations
+        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9  # v6.1.0
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          path: .test_durations
+          key: test-durations-${{ github.ref }}-${{ github.sha }}
+          restore-keys: |
+            test-durations-${{ github.ref }}-
+            test-durations-
+
+      - name: post-process test durations
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          if [[ -f .test_durations ]]; then
+            cp .test_durations .test_durations.mongodb
+          fi
+
+      - name: run pytest
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          export TEST_BOT_TOKEN_VAL=unpassword
+          # note: we do not use pytest-xdist (-n auto) here for now because they interfere with hiding the
+          # MONGODB_CONNECTION_STRING sensitive environment variable
+          if [[ -f .test_durations ]]; then
+            cp .test_durations .test_durations.${{ matrix.group }}
+          fi
+          pytest \
+            -v \
+            --splits 1 --group ${{ matrix.group }} \
+            --store-durations \
+            --durations-path=.test_durations.mongodb \
+            --splitting-algorithm least_duration \
+            --clean-durations \
+            --cov=conda_forge_tick \
+            --cov=tests \
+            --cov-config=.coveragerc \
+            --cov-report=term-missing \
+            --cov-report=xml \
+            --durations=10 \
+            -m "mongodb" \
+            tests
+        env:
+          MONGODB_CONNECTION_STRING: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000"
+          RUN_URL: ""
+          BOT_TOKEN: ${{ secrets.AUTOTICK_BOT_TOKEN }}
+          BOT_APP_ID: ${{ secrets.CF_BOT_DATA_MANAGER_APP_ID }}
+          BOT_PRIVATE_KEY: ${{ secrets.CF_BOT_DATA_MANAGER_PRIVATE_KEY }}
+
+      - name: upload test durations
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          name: test-durations-mongodb
+          path: .test_durations.mongodb
+          include-hidden-files: true
+
+      - name: upload coverage
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          name: coverage-mongodb
+          path: .coverage
+          include-hidden-files: true
+
+  test-coverage-and-durations:
+    name: test-coverage-and-durations
+    needs:
+      - tests
+      - tests-mongodb
+      - check
+    runs-on: ubuntu-slim
+    defaults:
+      run:
+        shell: bash -leo pipefail {0}
+    steps:
+      - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          environment-name: conda-forge-bot
+          create-args: >-
+            coverage
+            jq
+          condarc: |
+            channels:
+              - conda-forge
+
+      - name: download coverage artifacts
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          pattern: coverage-*
+
+      - name: combine coverage
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          coverage combine coverage-*/.coverage*
+          coverage xml
+
+      - name: upload codecov
+        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v5.1.8
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: cache test durations
+        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          path: .test_durations
+          key: test-durations-${{ github.ref }}-${{ github.sha }}
+          restore-keys: |
+            test-durations-${{ github.ref }}-
+            test-durations-
+
+      - name: download test duration artifacts
+        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          pattern: test-durations-*
+
+      - name: combine test durations
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        run: |
+          # see https://stackoverflow.com/a/71416016/1745538
+          jq 'reduce inputs as $i (.; . + $i)' test-durations-*/.test_durations.* > .test_durations
+
+      - name: upload test durations
+        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
+        if: ${{ needs.check.outputs.skip-check != 'true' }}
+        with:
+          name: test-durations
+          path: .test_durations
+          include-hidden-files: true
+
+  # this little bit follows the same pattern from conda-build
+  status:
+    needs:
+      - tests
+      - tests-mongodb
+      - test-coverage-and-durations
+      - check
+    if: '!cancelled()'
+    runs-on: ubuntu-slim
+    steps:
+      - name: determine success
+        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
+        with:
+          jobs: ${{ toJSON(needs) }}
